### ISSUE TITLE
Installation and usage

### ISSUE THREAD

**Issue by bede** [IlariaB/Newick-validator#1]
Hi there,
Thanks for sharing this project. I'm interested in using it, but the project has an unusual file structure, and the documentation appears to lack a clear minimal working example. It looks like one is supposed to import the newick_validator package, but it is not clear to me where this package is or how to install it.

Perhaps you could add to the readme some foolproof instructions explaining how to install the package from Github and validate a newick file (assuming that the user has created a python environment and installed the required dependencies). Thanks!

**Comment by sammyjava** [comment]
Fixed in a couple PRs, it should be
```
import Newick_Validator
```

**Comment by sammyjava** [comment]
And then you run
```
CLI.py <filename>
```
after making CLI.py executable.

**Comment by biomendi** [comment]
I am also interested in validating a newick file using the scripts in this project. However, after checking the readme, I find very difficult to understand what commands need to be executed to install and run the package. It would be a great help if you could please make a small step-by-step explanation.
